# frozen_string_literal: true

# Table: posts
# Columns:
#  id          | integer | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  title       | text    | NOT NULL
#  description | text    | NOT NULL
#  likes       | integer | NOT NULL DEFAULT 0
#  dislikes    | integer | NOT NULL DEFAULT 0
# Indexes:
#  posts_pkey | PRIMARY KEY btree (id)

class Post < Sequel::Model
  many_to_one :user
end
